"""
Reusable Clinical UI Components for HydroFed-ICAF Streamlit Application.
"""

import streamlit as st
import matplotlib.pyplot as plt

def render_header(title, subtitle=None, badge_text=None, badge_type="primary"):
    """Renders a standardized clinical page header with optional subtitle and badge."""
    badge_html = f'<span class="badge badge-{badge_type}" style="margin-left: 10px; vertical-align: middle;">{badge_text}</span>' if badge_text else ""
    st.markdown(f"""
    <div style="margin-bottom: 15px;">
        <h1 style="display: inline-block; margin-bottom: 2px;">{title}</h1>{badge_html}
        {f'<p style="color: #64748B; font-size: 0.95rem; margin-top: 2px; margin-bottom: 0;">{subtitle}</p>' if subtitle else ''}
    </div>
    """, unsafe_allow_html=True)

def render_patient_banner(patient_id, demographics=None):
    """Renders an active patient banner displaying demographics overview."""
    if not patient_id:
        st.markdown("""
        <div class="clinical-banner clinical-banner-warning">
            ⚠️ <b>No Active Patient Selected</b> — Please lookup or register a patient profile to enable diagnostics.
        </div>
        """, unsafe_allow_html=True)
        return

    demographics = demographics or {}
    age = demographics.get('age', 'N/A')
    gender = demographics.get('gender', 'N/A')
    diabetes = "Present" if demographics.get('diabetes') == 1 else "Absent"
    smoke = "Exposed" if demographics.get('passive_smoke_exposure') == 1 else "None"
    family = "Positive" if demographics.get('family_respiratory_history') == 1 else "Negative"

    st.markdown(f"""
    <div class="metric-card metric-card-primary" style="margin-bottom: 20px;">
        <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 10px;">
            <div>
                <span class="card-label">Active EHR Patient Workspace</span>
                <span style="font-size: 1.25rem; font-weight: 700; color: #173B65;">{patient_id}</span>
            </div>
            <div style="display: flex; gap: 20px; font-size: 0.85rem; color: #334155; flex-wrap: wrap;">
                <div><b>Age:</b> {age} Yrs</div>
                <div><b>Gender:</b> {gender}</div>
                <div><b>Diabetes:</b> {diabetes}</div>
                <div><b>Passive Smoke:</b> {smoke}</div>
                <div><b>Family History:</b> {family}</div>
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)

def render_metric_card(label, value, card_type="default", subtext=None, col=None):
    """Renders a styled metric card container."""
    type_class = f"metric-card-{card_type}" if card_type in ["primary", "danger", "success", "warning"] else ""
    subtext_html = f'<div style="font-size: 0.78rem; color: #64748B; margin-top: 4px;">{subtext}</div>' if subtext else ""
    html = f"""
    <div class="metric-card {type_class}">
        <span class="card-label">{label}</span>
        <div class="card-value">{value}</div>
        {subtext_html}
    </div>
    """
    if col:
        col.markdown(html, unsafe_allow_html=True)
    else:
        st.markdown(html, unsafe_allow_html=True)

def render_uncertainty_alert(uncertainty_val, threshold=0.15):
    """Renders a safety uncertainty boundary indicator."""
    if uncertainty_val > threshold:
        st.markdown(f"""
        <div class="clinical-banner clinical-banner-danger" style="display: flex; align-items: center; gap: 12px;">
            <span style="font-size: 1.5rem;">🚨</span>
            <div>
                <b>CLINICIAN REVIEW MANDATORY — PREDICTIVE UNCERTAINTY EXCEEDED</b><br>
                Model predictive uncertainty (<b>{uncertainty_val:.4f}</b>) exceeds the maximum autonomous threshold (<b>{threshold:.4f}</b>). 
                Autonomous indices are flagged as unreliable. Certified medical consultation is mandatory.
            </div>
        </div>
        """, unsafe_allow_html=True)
    else:
        st.markdown(f"""
        <div class="clinical-banner clinical-banner-success" style="display: flex; align-items: center; gap: 12px;">
            <span style="font-size: 1.5rem;">✅</span>
            <div>
                <b>SAFETY CONFIDENCE BOUNDARY NOMINAL</b><br>
                Model predictive uncertainty (<b>{uncertainty_val:.4f}</b>) is within nominal safety bounds (&le; {threshold:.4f}).
            </div>
        </div>
        """, unsafe_allow_html=True)

def render_disclaimer():
    """Renders the required clinical decision support and regulatory disclaimer box."""
    st.markdown("""
    <div class="disclaimer-card">
        <b>MANDATORY CLINICAL &amp; REGULATORY DISCLAIMER</b><br>
        This diagnostic report is generated by the HydroFed-ICAF automated clinical decision support system. 
        It is designed solely as an investigational and diagnostic support tool for licensed healthcare practitioners 
        and does not constitute a definitive medical diagnosis, autonomous therapeutic recommendation, or prescription. 
        Radiological interpretation must be confirmed by a certified physician in conjunction with the patient's comprehensive clinical history and physical examination.
    </div>
    """, unsafe_allow_html=True)

def setup_matplotlib_clinical_theme():
    """Sets up a clean, high-contrast clinical chart palette for Matplotlib."""
    plt.rcParams['font.family'] = 'sans-serif'
    plt.rcParams['font.sans-serif'] = ['Inter', 'Segoe UI', 'DejaVu Sans', 'Arial', 'Helvetica']
    plt.rcParams['text.color'] = '#1E293B'
    plt.rcParams['axes.labelcolor'] = '#1E293B'
    plt.rcParams['xtick.color'] = '#64748B'
    plt.rcParams['ytick.color'] = '#64748B'
    plt.rcParams['axes.edgecolor'] = '#CBD5E1'
    plt.rcParams['grid.color'] = '#E2E8F0'
    plt.rcParams['grid.alpha'] = 0.6
    plt.rcParams['figure.facecolor'] = '#FFFFFF'
    plt.rcParams['axes.facecolor'] = '#F8FAFC'
